create table if not exists public.transactions (
    id bigint generated by default as identity primary key,
    type text not null check (type in ('income', 'expense')),
    amount bigint not null check (amount > 0),
    category text not null,
    transaction_date date not null default current_date,
    description text not null default '',
    created_at timestamptz not null default now()
);

-- The Streamlit server uses the Supabase service-role key.
-- Therefore no client-side authentication is needed for this private app.
-- Keep SUPABASE_SERVICE_ROLE_KEY only in Streamlit Secrets.
